# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'
  imageName: 'mazihuk/pipelines-flask-docker'
  
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        # tags: |
        #   $(tag)
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'

    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhubconnection'
        repository: $(imageName)
        command: 'push'

    - task: CopyFiles@2
      inputs:
        Contents: |
          Contents: |
           **/manifests/deployment.yaml
           **/manifests/service.yaml
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'deploymentFolder'
        publishLocation: 'Container'


# # - stage: Deploy
# #   displayName: Deploy image to Kubernetes
# #   jobs:
# #   - deployment: Deploy
# #     dependsOn:
# #     environment: 'flaskenvironment'
# #     strategy:
# #       runOnce:
# #         deploy:
# #           steps:

#

# #           - task: Bash@3
# #             inputs:
# #               targetType: 'inline'
# #               script: |
#                 # Write your commands here
                
#                 #cd '$(Build.SourcesDirectory)'
#                 #ls
#                 pwd
#                 ls -l
#                 cd ..
#                 echo 'how are you'
              
# #          - task: KubernetesManifest@0
# #            inputs:
# #              action: 'deploy'
# #              kubernetesServiceConnection: 'flaskenvironment-Flaskdemocluster-default-1586793974934'
# #              manifests: '$(Build.ArtifactStagingDirectory)/manifests/*'
